language: python
python:
- '3.9'
install:
- pip install -r requirements.txt
script:
- pytest
before_install:
- openssl aes-256-cbc -K $encrypted_35c6b6a676e1_key -iv $encrypted_35c6b6a676e1_iv
  -in website.pem.enc -out website.pem -d
env:
  global:
  - secure: hoyThkcHQUtgBFwhqvQAa5i871/T5EXH4VWT13O3NF3JPgop3OOW9EBq0aeQeMRCbhexI45vizHzF9s+DZN9BuzSqyFCKLgDZ1hO9zox0u1dodueutxf382s/rw7HVg6PnEvDuwWPL3gK6XuiByTyBbv6ajYbcDlnWUfCYLAY3PbKPWMDxWpDTCH7lIPLM66I/dm6049ueJxWW9UeajxzKPVINEzqBx3E3t+KuQXafCzamJtEuh+FaNJx6fppXhTzuxsGNUihQPW9FFdjq/M9YwlXhthC8ZRTLK3rjtF6K7Fzdmz190ZIBwvl60va8T8rl/to5Ea9wCNHBAggfMudrJr32npiciT1U6eKZWVQcpthPEyKPjvo2/Ev+CGNKq0r1dKerqyYNTLGFkIJxzYcq7nt6wqIr0AWlNAeG852v/KZvRcPrlu5nfTiBl9obcsrEiMfRDnAOeepVHTgy0/a0VhpxChBc5Tx8XGEIdeFWjeoDNhY1I26DGWJHc45+UJy4oOdmRJEciorSaKu2+iUgyNcBxk3PNUrFzRUj3LrPO2dHJN1XM2hrn9rBcYxDzWVgqVNNSvmMkPNDA4Y6l4m32gevwbMlK/JfMjo0ObDBNXbx9OjHmdeIRfIHeteSMUzyacXofSe8PaZwAVzPdzW9Fqfov+icMvDNJTHc2b9tw=
  - secure: UncZ2HJTozp9ytTcmeMEmh4RxncHSE0CGO5fAAN0jAS6shIeM0AVtgGfiAWadVSFQfhPFnyJNeTmIHoCnoYYeJhd9y4tWDhSC7LSkTyTE7XCWPSKNBolN5Mp5KEUv03HNyT9PSCLJqyxrv5Gcu4Mefo6JgeOLXVj0flDiiBRXfJC95mx8n/7zpjKQ+Mrd+gCvHByeaa/5eeoOkpSS4c1wA46RDTKvtYzV21umYqYyssDyBehjFPxd7+cLXY8U9u1hg3SAICF0f7gfiAOSSoLto2RzOtVudPBLL5U5zMBwkbsfDGKl5vTuxALeAZlXLSVVQkX04Giju7KJMseyxFaib/CceuhQzO8VGMhTt3mT0GXB2i7PIHJbwNDOfEFViSz2TL6lx1+EJPrmh7Sf8/5o81Z4QbLt+xtGt7UdMD9hJlG6SZUH4lsmk3QOn563BOJNDMHGQkIvIOg5LLok1kHyiFIUVr1axJ24F4rihJG7U4QoRJcidIQVvdvjfkoFdp2umH1MLWOEqB3MnLKOYu6wLXXXDzED0Uy0meJJHSVkiN7A4wlCnbQPmnZgJfFn2KJ3elY7JQE8G/dRvOXC4Poo9LfC7MkK3bL3D4NN9XQiN5nrObInc8Z/Dg/IWz0AG2HVXF1gnr7ywR3IZOCk8SljnpJMv7r94k9BcVDDq0Vxks=
deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: main
