# Credits to https://github.com/seed-of-apricot/issue-list-readme
on:
  issues:
    types: [labeled, unlabeled]
  push:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        GITHUB_TOKEN: "${{ secrets.GTIHUB_TOKEN }}"
    - name: Auto Issue List in README
      uses: seed-of-apricot/issue-list-readme@v1.1.0
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        pattern: "<!-- openIssueTable -->"
        state: "open"
    - name: Completed Issue List
      uses: seed-of-apricot/issue-list-readme@v1.1.0
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        pattern: "<!-- closedIssueTable -->"
        state: "closed"

    - name: Add Updated Readme to Git
      uses: EndBug/add-and-commit@v4
      with:
        message: README.md has been re-written
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    - name: Push Updates to Git
      uses: ad-m/github-push-action@master
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
